spring:
  application:
    name: chat-management-gateway
  server:
    port: 8080
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
