server:
    port: 8080
spring:
  application:
    name: chat-management-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info


api:
  gateway:
    auth:
      key: $2a$12$Sis.IQrTEuVosgoIy3dssuubn3m/09y7m8R4wk5JMH14yZ0l3sQlK

  rate-limit:
    threshold: 10