CREATE USER chat_app_user WITH PASSWORD 'ChatApp2025';
CREATE DATABASE CHAT_MANAGE_DB OWNER chat_app_user;
CREATE DATABASE CHAT_MANAGE_DB2 OWNER chat_app_user;
CREATE DATABASE CHAT_MANAGE_DB3 OWNER chat_app_user;
GRANT ALL PRIVILEGES ON DATABASE chat_app_db TO chat_app_user;