FROM eclipse-temurin:21-jre-alpine AS build
WORKDIR /api-gateway
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /api-gateway
COPY target/ChatManagementGateway-0.0.1-SNAPSHOT.jar gateway.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "gateway.jar"]
